### PR TITLE
Throw error when the compiler is not supported

### PR DESCRIPTION
**Pull request by JackBoosY**
The current behavior will mislead the user into thinking that configuration was successful, when in fact it failed due to unsupported compiler version.

### CODE REVIEW

**Comment by JackBoosY** [comment]
Ref:
https://github.com/microsoft/vcpkg/issues/40290
https://github.com/microsoft/vcpkg/issues/40310
https://github.com/microsoft/vcpkg/issues/39573
https://github.com/microsoft/vcpkg/issues/39495
https://github.com/microsoft/vcpkg/issues/38498

**Comment by klemens-morgenstern** [comment]
That's not a solution, that would break any cmake build on compilers that don't support C++20.
The configuration is fine as is, you can build boost, just without cobalt. This requires a fix on vcpkg.

**Comment by JackBoosY** [comment]
> That's not a solution, that would break any cmake build on compilers that don't support C++20. The configuration is fine as is, you can build boost, just without cobalt. This requires a fix on vcpkg.

If I understand correctly, the configuration step will break when the compiler doesn't support cxx 20, isn't it?

**Comment by klemens-morgenstern** [comment]
Correct.

**Comment by JackBoosY** [comment]
> Correct.

So I don't know why this changes is incorrect.
If the compiler doesn't meet the requirements, it should be FAILED at configure step, not just return and pass.

**Comment by klemens-morgenstern** [comment]
Because this is built as part of boost. Your change would make configuring boost fail if the compiler isn't supported.

**Comment by JackBoosY** [comment]
> Because this is built as part of boost. Your change would make configuring boost fail if the compiler isn't supported.

So I assume this approach is flawed? If the user builds boost with a compiler that doesn't meet the requirements, the "correct" results obtained may be different from what is expected and the results can only be confirmed by the build log?

**Comment by klemens-morgenstern** [comment]
You assume wrongly. Boost is a library collection that has different requirements, such as C++20 for boost.cobalt.

Your proposed change is not a solution.

**Pull request closed without merging**
